### PR TITLE
Added mozilla section to code of conduct.

### PR DESCRIPTION
**Pull request by jrbenny35**
This incorporates mozilla's Code Of Conduct into ours. See #135 and #134

### CODE REVIEW

**Comment by jrbenny35** [comment]
@hackebrot I edited that fine in this PR.

**Comment by hackebrot** [comment]
@jrbenny35 Can you please remove the Contributor Covenant Code of Conduct text?

**Comment by jrbenny35** [comment]
> @jrbenny35 Can you please remove the Contributor Covenant Code of Conduct text?

The entire thing??

**Comment by hackebrot** [comment]
@jrbenny35 Please don't merge pull requests without approval from a reviewer or at least adding a comment that explains what's been discussed offline, so that folks who read up on this pull request or related issues know why we have merged these changes.

**Pull request merged**
