### PR TITLE
#20 #bugfix Added pyup

### PR DESCRIPTION
**Pull request by aayush420**
- Added Pyup config file and did test runs at pyup.io
- Configuration working properly.
- @jrbenny35 Thanks for helping me out

### CODE REVIEW

**Comment by jrbenny35** [comment]
@aayush420 thanks for the PR, I hope you stick around and help out some more 😁

**Comment by hackebrot** [comment]
Thanks so much for your contribution @aayush420! It is much appreciated 🙇 

Would you mind sharing with us how you discovered **redash-ui-tests** and this task?

**Comment by aayush420** [comment]
@hackebrot and @jrbenny35 , Sure, I'll definitely try contribute more.
I was thinking of doing contributions to the community. 
I don't remember how I got here. Most probably through Github search only, I guess.

**Comment by hackebrot** [comment]
Ok, I'm happy to hear that 😃

**Pull request merged**
