### PR TITLE
Start documentation

### LINKED ISSUE #35: Start documentation
Start documentation with [mkdocs](https://www.mkdocs.org/) and set up [readthedocs](https://readthedocs.org/) 📝

### PR DESCRIPTION
**Pull request by hackebrot**
Resolve #35 📝

### CODE REVIEW

**Comment by jrbenny35** [comment]
Does this deploy to readthedocs? Or are we not doing that yet.

**Comment by hackebrot** [comment]
@jrbenny35 I imported this project into readthedocs already, but the files added in this PR are required to build the documentation.

**Comment by jrbenny35** [comment]
Ah yes, I forgot readthedocs just watches the repo and builds on changes.

**Comment by hackebrot** [comment]
https://redash-ui-tests.readthedocs.io/en/latest/

**Comment by jezdez** [comment]
@hackebrot Mind adding me to the RTD project?

**Comment by hackebrot** [comment]
@jezdez Done! Let me know if it works.

**Pull request merged**
