### PR TITLE
Updates to api calls that have changed in upstream.

### PR DESCRIPTION
**Pull request by jrbenny35**
There have been some changes to, specifically, the users api endpoint for upstream redash. Our integration tests are failing on the upstream circle ci job due to this. This patch should fix those.

### CODE REVIEW

**Comment by jrbenny35** [comment]
Wait, why was this merged?

**Comment by hackebrot** [comment]
Wasn't that ready to be merged @jrbenny35?

**Comment by jrbenny35** [comment]
> Wasn't that ready to be merged @jrbenny35? 

Not at all. I opened #75 because of the changes I would have to make to this, but we never decided on what we wanted to do.

**Comment by hackebrot** [comment]
I reverted the merge and created #80.

**Pull request merged**
